# Generated by Django 5.1.4 on 2024-12-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='fonctionnalite_valide',
            field=models.BooleanField(default=False),
        ),
    ]
